[workspace]
members = [
    "contracts/rust/wasmlib",
    "contracts/rust/erc20",
    "articles/tutorial/example-tutorial",
    "contracts/rust/testcore",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

