name: MyWorld
description: MyWorld description
structs:
  Treasure:
    amount: Int64 // how much to deposit
    name: String // human readible name
    owner: AgentID // who deposits the treasure
typedefs: {}
state:
  owner: AgentID // current owner of this smart contract
  treasures: Treasure[] // all deposits ever made
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
  depositTreasure:
    params:
      treasure: Treasure
views:
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract
  getAllTreasures:
    results:
      treasures: Treasure[]

